# Generated by Django 5.2.3 on 2025-07-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique department name.', max_length=100, unique=True, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, help_text='Short description about the department.', null=True, verbose_name='Description')),
                ('icon', models.ImageField(blank=True, help_text='Upload department icon (optional).', null=True, upload_to='department_icons/', verbose_name='Department Icon')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to deactivate the department without deleting it.', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
                'permissions': [('can_view_department', 'Can view department')],
            },
        ),
    ]
